POST  http://localhost:3000/login
Content-Type: application/json

{
    "username": "john_doe",
    "email": "john@example.com",
   
    "password": "password"
}


###

GET http://localhost:3000/profile 
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJpYXQiOjE3MDg2ODEwNzAsImV4cCI6MTcwODY4ODI3MH0.dn_9lUu9kNUcFbJrbdTMZH6BsMHtJsN6NlGlunDCkio
